//! Throwaway git repositories for runtime integration tests.
//!
//! Shared by `mod fixture;` from the test files that need a real repository to
//! branch a worktree from. Cargo also compiles this file as a test target of its
//! own — it contains no tests, and the `dead_code` allow below is what keeps that
//! empty target, and any test file that uses only part of this module, from
//! failing the `-D warnings` gate.
//!
//! # Two builders, and why the distinction is load bearing
//!
//! [`trivial_repo`] is a one-commit repository holding a file that compiles. It
//! is a *tree to branch a worktree from* and nothing more: the tests that use it
//! assert about paths, containment, environments and process groups, and none of
//! them ever runs a build over it.
//!
//! [`broken_crate`] is a real cargo package whose own test suite fails. It is
//! what a repair capability has to be pointed at before "the check decides"
//! means anything at all — over `trivial_repo`, a `write_file` that silently did
//! nothing would leave a tree that still passes, and every assertion about a
//! verdict would pass with it. [`check`] is the same command the capability's
//! host runs, exposed here so the fixture can prove *of itself* that it starts
//! failing and ends passing.
#![allow(dead_code)]

use std::path::{Path, PathBuf};
use std::process::Stdio;

/// The defect [`broken_crate`] ships with: an off-by-one that compiles cleanly
/// and fails the package's own test, so a repair has to be a real edit rather
/// than a syntax fix a formatter could have made.
pub const BROKEN: &str = "pub fn last_index(len: usize) -> usize { len }\n";

/// The edit that makes [`check`] pass.
pub const REPAIRED: &str = "pub fn last_index(len: usize) -> usize { len - 1 }\n";

/// A one-commit repository holding a trivial file.
///
/// Not a cargo package and not broken — deliberately, because nothing that uses
/// it runs a build. The identity is passed per-invocation rather than assumed: a
/// CI runner has no `user.email` configured and `git commit` refuses outright
/// without one, so a fixture that relied on the ambient config would pass
/// locally and fail there.
///
/// `target/` is gitignored so that `git status --porcelain` over a worktree of
/// this repository reports what a build *changed*, not what it *produced*.
pub fn trivial_repo(dir: &Path) -> PathBuf {
    let repo = dir.join("fixture");
    std::fs::create_dir_all(repo.join("src")).unwrap();
    std::fs::write(repo.join("src/lib.rs"), "pub fn f() {}\n").unwrap();
    std::fs::write(repo.join(".gitignore"), "target/\n").unwrap();
    commit(&repo, "fixture");
    repo
}

/// A deliberately broken zero-dependency Rust crate, as a git repository.
///
/// Zero dependencies so `cargo test --offline` needs nothing from the network
/// and no registry index has to exist. The package's integration test asserts
/// what `last_index` is for, and [`BROKEN`] does not satisfy it, so the crate
/// compiles and its check fails — which is the shape a repair capability must be
/// given if the outcome is to be decided by the check rather than by the model.
///
/// `target/` **and** `Cargo.lock` are gitignored. Both matter and the second is
/// the one that is easy to miss: cargo writes a lock file on the first run even
/// for a package with no dependencies, so without the second line
/// `changed_files()` over a worktree that ran its check reports two paths, only
/// one of which anybody edited. A lock file regenerated by the check is not a
/// repair, and counting it spends the changed-file cap on noise and puts a
/// fabricated path into published evidence.
pub fn broken_crate(dir: &Path) -> PathBuf {
    let repo = dir.join("fixture");
    std::fs::create_dir_all(repo.join("src")).unwrap();
    std::fs::create_dir_all(repo.join("tests")).unwrap();
    std::fs::write(
        repo.join("Cargo.toml"),
        "[package]\nname = \"fixture\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n\
         [dependencies]\n",
    )
    .unwrap();
    std::fs::write(repo.join("src/lib.rs"), BROKEN).unwrap();
    std::fs::write(
        repo.join("tests/repair.rs"),
        "#[test]\nfn the_last_index_is_one_before_the_length() {\n    \
         assert_eq!(fixture::last_index(3), 2);\n}\n",
    )
    .unwrap();
    std::fs::write(repo.join(".gitignore"), "target/\nCargo.lock\n").unwrap();
    commit(&repo, "the broken fixture");
    repo
}

/// What running a check over a repository said.
///
/// The captured output is kept rather than discarded because half the calls to
/// [`check`] *expect* a failure and the other half expect a pass — so when the
/// half that expects a pass is the one that fails, the assertion has to be able
/// to say why, and a check whose output went to `/dev/null` cannot.
pub struct CheckResult {
    pub code: Option<i32>,
    pub output: String,
}

impl CheckResult {
    pub fn success(&self) -> bool {
        self.code == Some(0)
    }
}

/// Run `cargo test --offline` over `repo`, under an environment built from
/// nothing.
///
/// The same command this module's consumers configure a capability's host check
/// with, and run the same way `Workspace::run` runs it: the environment is
/// cleared and rebuilt, so this process's credentials cannot reach a child, and
/// `HOME` points at a throwaway directory beside the repository rather than at
/// the operator's.
///
/// That `HOME` is what keeps a nested check hermetic. `CARGO_HOME` defaults to
/// `$HOME/.cargo`, so each repository gets a cargo home of its own and two
/// checks running concurrently — which is what `cargo test` does to this file's
/// consumers — never contend on one package cache.
///
/// The inherited set is `PATH` and `RUSTUP_HOME`, and it is deliberately the
/// same set `command.rs` allows, for the same reason and with the same
/// justification: both are toolchain *locators*, neither is an authority. It
/// matters that the two agree. A helper that inherited more than the product
/// does would pass here and leave the capability's own check failing; one that
/// inherited less would fail here for a reason the product does not have. They
/// share fate on purpose, so a divergence is one failure with one cause.
pub fn check(repo: &Path) -> CheckResult {
    let home = repo.with_extension("check-home");
    std::fs::create_dir_all(&home).unwrap();
    let mut command = std::process::Command::new("cargo");
    command
        .args(["test", "--offline"])
        .current_dir(repo)
        .env_clear()
        .env("HOME", &home)
        .env(
            "PATH",
            std::env::var("PATH").unwrap_or_else(|_| "/usr/bin:/bin".to_string()),
        )
        .env("LANG", "C")
        .stdin(Stdio::null())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped());
    // Where cargo is a rustup proxy it resolves its toolchain through this and
    // refuses without it, and `HOME` above has just been pointed somewhere with
    // no `.rustup` in it.
    if let Ok(rustup_home) = std::env::var("RUSTUP_HOME") {
        command.env("RUSTUP_HOME", rustup_home);
    }
    let output = command
        .output()
        .unwrap_or_else(|source| panic!("could not run cargo in {}: {source}", repo.display()));
    CheckResult {
        code: output.status.code(),
        output: format!(
            "{}{}",
            String::from_utf8_lossy(&output.stdout),
            String::from_utf8_lossy(&output.stderr)
        ),
    }
}

/// Initialise `repo` as a git repository with everything in it committed.
fn commit(repo: &Path, message: &str) {
    git(repo, &["init", "-q", "."]);
    git(repo, &["add", "-A"]);
    git(
        repo,
        &[
            "-c",
            "user.email=t@t",
            "-c",
            "user.name=t",
            "commit",
            "-qm",
            message,
        ],
    );
}

/// Run git in `dir`, panicking with its stderr if it fails.
///
/// A fixture that failed silently would surface as an unrelated assertion
/// failure further down the test, so the panic carries what git actually said.
pub fn git(dir: &Path, args: &[&str]) {
    let output = std::process::Command::new("git")
        .args(args)
        .current_dir(dir)
        .output()
        .unwrap_or_else(|source| panic!("could not run git {args:?}: {source}"));
    assert!(
        output.status.success(),
        "git {args:?} failed: {}",
        String::from_utf8_lossy(&output.stderr)
    );
}

/// What `git status --porcelain` reports as changed in `dir`, as plain paths.
///
/// Used to assert that a repository is *unmutated* — which is the whole of what
/// M1 leaves behind at the fixture, the repair itself having lived and died in
/// a per-attempt worktree.
pub fn changed_files(dir: &Path) -> Vec<String> {
    let output = std::process::Command::new("git")
        .args(["status", "--porcelain"])
        .current_dir(dir)
        .output()
        .unwrap_or_else(|source| panic!("could not run git status: {source}"));
    assert!(output.status.success(), "git status failed in {dir:?}");
    String::from_utf8_lossy(&output.stdout)
        .lines()
        .map(|line| line[3..].trim().to_string())
        .collect()
}
